docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - umask 0022
    - apk add git
    - apk add curl
    - git submodule init
    - git submodule update
    - chmod -R og-w .
    - cd ampache && docker build -t jgoerzen/ampache .
    - cd ../ampache-mysql && docker build -t jgoerzen/ampache-mysql .
    - docker tag jgoerzen/ampache jgoerzen/ampache:5.6.0
    - docker tag jgoerzen/ampache-mysql jgoerzen/ampache-mysql:5.6.0
    - docker push jgoerzen/ampache
    - docker push jgoerzen/ampache:5.6.0
    - docker push jgoerzen/ampache-mysql
    - docker push jgoerzen/ampache-mysql:5.6.0
  only:
    - master
